import { generateHash } from "../../domain/hash";
import { MarkdownString, Tag, Task, TaskId, TaskTitle } from "../../domain/model";

interface buildTaskArgs {
  id?: TaskId;
  title?: TaskTitle;
  content?: MarkdownString;
  created?: Date;
  updated?: Date;
  tags?: Set<Tag>;
  blockedBy?: Set<TaskId>;
  blocks?: Set<TaskId>;
  completed?: boolean;
}
export default function task({
  id,
  title,
  content,
  created,
  updated,
  tags,
  blockedBy,
  blocks,
  completed,
}: buildTaskArgs): Task {
  return {
    id: id || generateHash(),
    title: title || "autogenerated task title",
    content: content || "autogenerated task content",
    created: created || new Date(),
    updated: updated || new Date(),
    tags: tags || new Set<Tag>(),
    blockedBy: blockedBy || new Set<TaskId>(),
    blocks: blocks || new Set<TaskId>(),
    completed: completed || false,
  }
}