import { generateHash } from "../../domain/hash";
import { Tag, View, ViewContentLine, ViewId, ViewTitle } from "../../domain/model";

interface buildViewArgs {
  id?: ViewId;
  title?: ViewTitle;
  created?: Date;
  updated?: Date;
  tags?: Set<Tag>;
  content?: ViewContentLine[];
}

export default function view({
  id,
  title,
  created,
  updated,
  tags,
  content,
}: buildViewArgs): View {
  return {
    id: id || generateHash(),
    title: title || "autogenerated task title",
    created: created || new Date(),
    updated: updated || new Date(),
    tags: tags || new Set<Tag>(),
    content: content || [{
      completed: false,
      title: "autogenerated task yet to be created",
      id: undefined,
    }],
  }
}